version: "3.4"
services:
    sdc.api.fe.simpledemo.onap.org:
        image: mock-sdc:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.2
    aai.api.sparky.simpledemo.onap.org:
        image: mock-aai:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.3
    so.api.simpledemo.onap.org:
        image: mock-so:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.4
    sdnc.api.simpledemo.onap.org:
        image: mock-sdnc:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.5
    clamp.api.simpledemo.onap.org:
        image: mock-clamp:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.6
    cds.api.simpledemo.onap.org:
        image: mock-cds:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.7
    msb.k8s.api.simpledemo.onap.org:
        image: mock-msb-k8s:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.8
    ves.api.simpledemo.onap.org:
        image: mock-ves:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.9
    dmaap.api.simpledemo.onap.org:
        image: mock-dmaap:latest
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.10

networks:
    sdk_integration:
        ipam:
            config:
                - subnet: 172.20.0.0/24