version: "3.4"
services:
    sdc.api.fe.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-sdc:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.2
    aai.api.sparky.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-aai:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.3
    so.api.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-so:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.4
    sdnc.api.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-sdnc:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.5
    clamp.api.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-clamp:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.6
    cds.api.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-cds:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.7
    msb.k8s.api.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-k8s:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.8
    ves.api.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-ves:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.9
    dmaap.api.simpledemo.onap.org:
        image: nexus3.onap.org:10003/onap/onap-component-mock-dmaap:master
        networks:
            sdk_integration:
                ipv4_address: 172.20.0.10

networks:
    sdk_integration:
        ipam:
            config:
                - subnet: 172.20.0.0/24